version: '3.7'

services:
  # frontend:
  #   restart: always
  #   build:
  #     context: ${PWD}
  #     dockerfile: docker/frontend.DockerFile
  #   image: frontend:0.0.1
  #   platform: linux/amd64
  #   ports:
  #     - "6006:6006"

  minio:
    image: quay.io/minio/minio:latest
    volumes:
      - ${PWD}/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ../.env
    command: minio server /data --console-address ":9001"

  mlflow-server:
    depends_on: 
     - minio
    restart: always
    # user: ${USER}:${USER}
    build:
      context: ${PWD}
    container_name: mlflow-server
    image: ghcr.io/mlflow/mlflow:v2.4.1
    ports:
      - "127.0.0.1:5005:5005"
    env_file:
      - ../.env
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://s3:9000
    volumes:
      - ${PWD}/models:/models
    entrypoint: mlflow server --host 0.0.0.0 --port 5005 --backend-store-uri sqlite:///models/mlflow.db --default-artifact-root s3://mlflow 
