version: '3.7'

services:
  # frontend:
  #   restart: always
  #   build:
  #     context: ${PWD}
  #     dockerfile: docker/frontend.DockerFile
  #   image: frontend:0.0.1
  #   platform: linux/amd64
  #   ports:
  #     - "6006:6006"

  minio:
    container_name: minio
    image: quay.io/minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ../.env
    volumes:
      - ${PWD}/minio:/data
    command: minio server /data --console-address ":9001"

  mlflow:
    depends_on: 
     - minio
    restart: always
    container_name: mlflow
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5005:5005"
    env_file:
      - ../.env
    volumes:
      - ${PWD}/data/db:/db
    entrypoint: >
      bash -c "pip install boto3 
      && mlflow server --backend-store-uri sqlite:///db/mlflow.db --default-artifact-root s3://mlflow/ --artifacts-destination s3://mlflow/ --host 0.0.0.0 --port 5005"

    # 
    # user: ${USER}:${USER}
    # build:
    #   context: ${PWD}