version: "3.2"
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.3.0
    build:
      context: ${PWD}
    # user: ${USER}:${GROUP:?"Please run as follows 'USER=$(id -u) GROUP=$(id -g) docker-compose up'"}
    restart: always
    expose:
      - 5005
    ports:
      - "5005:5005"
    container_name: mlflow
    volumes:
      - ${PWD}/models:/models
    command: mlflow server --host 0.0.0.0 --port 5005 --backend-store-uri sqlite:///models/mlflow.db --default-artifact-root '/models/artifacts'
